"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .deletedataset import DeleteDatasetRequest, DeleteDatasetRequestTypedDict
from .deleteliterature import DeleteLiteratureRequest, DeleteLiteratureRequestTypedDict
from .deleteorganism import DeleteOrganismRequest, DeleteOrganismRequestTypedDict
from .deleteproteinsequence import DeleteProteinSequenceRequest, DeleteProteinSequenceRequestTypedDict
from .deletesubstrate import DeleteSubstrateRequest, DeleteSubstrateRequestTypedDict
from .getdatasetbyid import GetDatasetByIDRequest, GetDatasetByIDRequestTypedDict
from .getdatasets import GetDatasetsRequest, GetDatasetsRequestTypedDict
from .getliteraturebyid import GetLiteratureByIDRequest, GetLiteratureByIDRequestTypedDict
from .getliteratures import GetLiteraturesRequest, GetLiteraturesRequestTypedDict
from .getorganismbyid import GetOrganismByIDRequest, GetOrganismByIDRequestTypedDict
from .getorganisms import GetOrganismsRequest, GetOrganismsRequestTypedDict
from .getproteinsequencebyid import GetProteinSequenceByIDRequest, GetProteinSequenceByIDRequestTypedDict
from .getproteinsequences import GetProteinSequencesRequest, GetProteinSequencesRequestTypedDict
from .getsubstratebyid import GetSubstrateByIDRequest, GetSubstrateByIDRequestTypedDict
from .getsubstrates import GetSubstratesRequest, GetSubstratesRequestTypedDict
from .partialupdatedataset import PartialUpdateDatasetRequest, PartialUpdateDatasetRequestTypedDict
from .partialupdateliterature import PartialUpdateLiteratureRequest, PartialUpdateLiteratureRequestTypedDict
from .partialupdateorganism import PartialUpdateOrganismRequest, PartialUpdateOrganismRequestTypedDict
from .partialupdateproteinsequence import PartialUpdateProteinSequenceRequest, PartialUpdateProteinSequenceRequestTypedDict
from .partialupdatesubstrate import PartialUpdateSubstrateRequest, PartialUpdateSubstrateRequestTypedDict
from .updatedataset import UpdateDatasetRequest, UpdateDatasetRequestTypedDict
from .updateliterature import UpdateLiteratureRequest, UpdateLiteratureRequestTypedDict
from .updateorganism import UpdateOrganismRequest, UpdateOrganismRequestTypedDict
from .updateproteinsequence import UpdateProteinSequenceRequest, UpdateProteinSequenceRequestTypedDict
from .updatesubstrate import UpdateSubstrateRequest, UpdateSubstrateRequestTypedDict

__all__ = ["DeleteDatasetRequest", "DeleteDatasetRequestTypedDict", "DeleteLiteratureRequest", "DeleteLiteratureRequestTypedDict", "DeleteOrganismRequest", "DeleteOrganismRequestTypedDict", "DeleteProteinSequenceRequest", "DeleteProteinSequenceRequestTypedDict", "DeleteSubstrateRequest", "DeleteSubstrateRequestTypedDict", "GetDatasetByIDRequest", "GetDatasetByIDRequestTypedDict", "GetDatasetsRequest", "GetDatasetsRequestTypedDict", "GetLiteratureByIDRequest", "GetLiteratureByIDRequestTypedDict", "GetLiteraturesRequest", "GetLiteraturesRequestTypedDict", "GetOrganismByIDRequest", "GetOrganismByIDRequestTypedDict", "GetOrganismsRequest", "GetOrganismsRequestTypedDict", "GetProteinSequenceByIDRequest", "GetProteinSequenceByIDRequestTypedDict", "GetProteinSequencesRequest", "GetProteinSequencesRequestTypedDict", "GetSubstrateByIDRequest", "GetSubstrateByIDRequestTypedDict", "GetSubstratesRequest", "GetSubstratesRequestTypedDict", "PartialUpdateDatasetRequest", "PartialUpdateDatasetRequestTypedDict", "PartialUpdateLiteratureRequest", "PartialUpdateLiteratureRequestTypedDict", "PartialUpdateOrganismRequest", "PartialUpdateOrganismRequestTypedDict", "PartialUpdateProteinSequenceRequest", "PartialUpdateProteinSequenceRequestTypedDict", "PartialUpdateSubstrateRequest", "PartialUpdateSubstrateRequestTypedDict", "UpdateDatasetRequest", "UpdateDatasetRequestTypedDict", "UpdateLiteratureRequest", "UpdateLiteratureRequestTypedDict", "UpdateOrganismRequest", "UpdateOrganismRequestTypedDict", "UpdateProteinSequenceRequest", "UpdateProteinSequenceRequestTypedDict", "UpdateSubstrateRequest", "UpdateSubstrateRequestTypedDict"]
