"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pypazy.types import BaseModel
from pypazy.utils import FieldMetadata, QueryParamMetadata
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class GetLiteraturesRequestTypedDict(TypedDict):
    limit: NotRequired[int]
    r"""Number of results to return per page."""
    offset: NotRequired[int]
    r"""The initial index from which to return the results."""
    

class GetLiteraturesRequest(BaseModel):
    limit: Annotated[Optional[int], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = None
    r"""Number of results to return per page."""
    offset: Annotated[Optional[int], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = None
    r"""The initial index from which to return the results."""
    
