"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pypazy.models.components import patchedliterature as components_patchedliterature
from pypazy.types import BaseModel
from pypazy.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class PartialUpdateLiteratureRequestTypedDict(TypedDict):
    id: str
    patched_literature: NotRequired[components_patchedliterature.PatchedLiteratureTypedDict]
    

class PartialUpdateLiteratureRequest(BaseModel):
    id: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    patched_literature: Annotated[Optional[components_patchedliterature.PatchedLiterature], FieldMetadata(request=RequestMetadata(media_type="application/json"))] = None
    
