"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pypazy.models.components import patchedsubstrate as components_patchedsubstrate
from pypazy.types import BaseModel
from pypazy.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class PartialUpdateSubstrateRequestTypedDict(TypedDict):
    id: str
    patched_substrate: NotRequired[components_patchedsubstrate.PatchedSubstrateTypedDict]
    

class PartialUpdateSubstrateRequest(BaseModel):
    id: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    patched_substrate: Annotated[Optional[components_patchedsubstrate.PatchedSubstrate], FieldMetadata(request=RequestMetadata(media_type="application/json"))] = None
    
