"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pypazy.models.components import patcheddataset as components_patcheddataset
from pypazy.types import BaseModel
from pypazy.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class PartialUpdateDatasetRequestTypedDict(TypedDict):
    id: str
    patched_dataset: NotRequired[components_patcheddataset.PatchedDatasetTypedDict]
    

class PartialUpdateDatasetRequest(BaseModel):
    id: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    patched_dataset: Annotated[Optional[components_patcheddataset.PatchedDataset], FieldMetadata(request=RequestMetadata(media_type="application/json"))] = None
    
