"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pypazy.models.components import patchedproteinsequence as components_patchedproteinsequence
from pypazy.types import BaseModel
from pypazy.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class PartialUpdateProteinSequenceRequestTypedDict(TypedDict):
    id: str
    patched_protein_sequence: NotRequired[components_patchedproteinsequence.PatchedProteinSequenceTypedDict]
    

class PartialUpdateProteinSequenceRequest(BaseModel):
    id: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    patched_protein_sequence: Annotated[Optional[components_patchedproteinsequence.PatchedProteinSequence], FieldMetadata(request=RequestMetadata(media_type="application/json"))] = None
    
