"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pypazy.models.components import proteinsequence_input as components_proteinsequence_input
from pypazy.types import BaseModel
from pypazy.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import TypedDict
from typing_extensions import Annotated


class UpdateProteinSequenceRequestTypedDict(TypedDict):
    id: str
    protein_sequence: components_proteinsequence_input.ProteinSequenceInputTypedDict
    

class UpdateProteinSequenceRequest(BaseModel):
    id: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    protein_sequence: Annotated[components_proteinsequence_input.ProteinSequenceInput, FieldMetadata(request=RequestMetadata(media_type="application/json"))]
    
