"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pypazy.models.components import literature_input as components_literature_input
from pypazy.types import BaseModel
from pypazy.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import TypedDict
from typing_extensions import Annotated


class UpdateLiteratureRequestTypedDict(TypedDict):
    id: str
    literature: components_literature_input.LiteratureInputTypedDict
    

class UpdateLiteratureRequest(BaseModel):
    id: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    literature: Annotated[components_literature_input.LiteratureInput, FieldMetadata(request=RequestMetadata(media_type="application/json"))]
    
