"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pypazy.models.components import organism_input as components_organism_input
from pypazy.types import BaseModel
from pypazy.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import TypedDict
from typing_extensions import Annotated


class UpdateOrganismRequestTypedDict(TypedDict):
    id: str
    organism: components_organism_input.OrganismInputTypedDict
    

class UpdateOrganismRequest(BaseModel):
    id: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    organism: Annotated[components_organism_input.OrganismInput, FieldMetadata(request=RequestMetadata(media_type="application/json"))]
    
