"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pypazy.types import BaseModel
from pypazy.utils import FieldMetadata
from typing import TypedDict
from typing_extensions import Annotated


class LiteratureInputTypedDict(TypedDict):
    doi: str
    title: str
    authors: str
    journal: str
    year: int
    

class LiteratureInput(BaseModel):
    doi: Annotated[str, FieldMetadata(form=True, multipart=True)]
    title: Annotated[str, FieldMetadata(form=True, multipart=True)]
    authors: Annotated[str, FieldMetadata(form=True, multipart=True)]
    journal: Annotated[str, FieldMetadata(form=True, multipart=True)]
    year: Annotated[int, FieldMetadata(form=True, multipart=True)]
    
