"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pypazy.types import BaseModel
from typing import TypedDict


class LiteratureTypedDict(TypedDict):
    id: int
    doi: str
    title: str
    authors: str
    journal: str
    year: int
    

class Literature(BaseModel):
    id: int
    doi: str
    title: str
    authors: str
    journal: str
    year: int
    
