"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .proteinsequence import ProteinSequence, ProteinSequenceTypedDict
from pydantic import model_serializer
from pypazy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class PaginatedProteinSequenceListTypedDict(TypedDict):
    count: NotRequired[int]
    next: NotRequired[Nullable[str]]
    previous: NotRequired[Nullable[str]]
    results: NotRequired[List[ProteinSequenceTypedDict]]
    

class PaginatedProteinSequenceList(BaseModel):
    count: Optional[int] = None
    next: OptionalNullable[str] = UNSET
    previous: OptionalNullable[str] = UNSET
    results: Optional[List[ProteinSequence]] = None
    
    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["count", "next", "previous", "results"]
        nullable_fields = ["next", "previous"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields
                or (
                    k in optional_fields
                    and k in nullable_fields
                    and (
                        self.__pydantic_fields_set__.intersection({n})
                        or k in null_default_fields
                    )  # pylint: disable=no-member
                )
            ):
                m[k] = val

        return m
        
