"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .proteinsequence_input import ProteinSequenceInput, ProteinSequenceInputTypedDict
from pypazy.types import BaseModel
from pypazy.utils import FieldMetadata, FormMetadata, MultipartFormMetadata
from typing import List, Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class PatchedDatasetTypedDict(TypedDict):
    protein: NotRequired[List[ProteinSequenceInputTypedDict]]
    accession: NotRequired[str]
    database: NotRequired[str]
    

class PatchedDataset(BaseModel):
    protein: Annotated[Optional[List[ProteinSequenceInput]], FieldMetadata(form=FormMetadata(json=True), multipart=MultipartFormMetadata(json=True))] = None
    accession: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    database: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    
