"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .literature_input import LiteratureInput, LiteratureInputTypedDict
from .organism_input import OrganismInput, OrganismInputTypedDict
from .substrate_input import SubstrateInput, SubstrateInputTypedDict
from pypazy.types import BaseModel
from pypazy.utils import FieldMetadata, FormMetadata, MultipartFormMetadata
from typing import List, Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class PatchedProteinSequenceTypedDict(TypedDict):
    organisms: NotRequired[List[OrganismInputTypedDict]]
    substrates: NotRequired[List[SubstrateInputTypedDict]]
    literature: NotRequired[List[LiteratureInputTypedDict]]
    name: NotRequired[str]
    amino_acid_sequence: NotRequired[str]
    verified_activity: NotRequired[bool]
    

class PatchedProteinSequence(BaseModel):
    organisms: Annotated[Optional[List[OrganismInput]], FieldMetadata(form=FormMetadata(json=True), multipart=MultipartFormMetadata(json=True))] = None
    substrates: Annotated[Optional[List[SubstrateInput]], FieldMetadata(form=FormMetadata(json=True), multipart=MultipartFormMetadata(json=True))] = None
    literature: Annotated[Optional[List[LiteratureInput]], FieldMetadata(form=FormMetadata(json=True), multipart=MultipartFormMetadata(json=True))] = None
    name: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    amino_acid_sequence: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    verified_activity: Annotated[Optional[bool], FieldMetadata(form=True, multipart=True)] = None
    
