"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pypazy.types import BaseModel
from pypazy.utils import FieldMetadata
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class PatchedSubstrateTypedDict(TypedDict):
    name: NotRequired[str]
    smiles: NotRequired[str]
    inchikey: NotRequired[str]
    abbreviation: NotRequired[str]
    

class PatchedSubstrate(BaseModel):
    name: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    smiles: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    inchikey: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    abbreviation: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    
