"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .literature import Literature, LiteratureTypedDict
from .organism import Organism, OrganismTypedDict
from .substrate import Substrate, SubstrateTypedDict
from pypazy.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class ProteinSequenceTypedDict(TypedDict):
    id: int
    organisms: List[OrganismTypedDict]
    substrates: List[SubstrateTypedDict]
    literature: List[LiteratureTypedDict]
    name: str
    amino_acid_sequence: NotRequired[str]
    verified_activity: NotRequired[bool]
    

class ProteinSequence(BaseModel):
    id: int
    organisms: List[Organism]
    substrates: List[Substrate]
    literature: List[Literature]
    name: str
    amino_acid_sequence: Optional[str] = None
    verified_activity: Optional[bool] = None
    
