"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pypazy.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class SubstrateTypedDict(TypedDict):
    id: int
    name: str
    abbreviation: str
    smiles: NotRequired[str]
    inchikey: NotRequired[str]
    

class Substrate(BaseModel):
    id: int
    name: str
    abbreviation: str
    smiles: Optional[str] = None
    inchikey: Optional[str] = None
    
