"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pypazy.types import BaseModel
from pypazy.utils import FieldMetadata
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class SubstrateInputTypedDict(TypedDict):
    name: str
    abbreviation: str
    smiles: NotRequired[str]
    inchikey: NotRequired[str]
    

class SubstrateInput(BaseModel):
    name: Annotated[str, FieldMetadata(form=True, multipart=True)]
    abbreviation: Annotated[str, FieldMetadata(form=True, multipart=True)]
    smiles: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    inchikey: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    
