"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from pazy import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Literature:
    id: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    doi: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('doi') }})
    title: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('title') }})
    authors: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('authors') }})
    journal: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('journal') }})
    year: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('year') }})
    

