"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from pazy import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class OrganismInput:
    UNSET='__SPEAKEASY_UNSET__'
    scientific_name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('scientific_name') }, 'form': { 'field_name': 'scientific_name' }, 'multipart_form': { 'field_name': 'scientific_name' }})
    phylum: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('phylum'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'phylum' }, 'multipart_form': { 'field_name': 'phylum' }})
    ncbi_taxonomy_id: Optional[int] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('ncbi_taxonomy_id'), 'exclude': lambda f: f is OrganismInput.UNSET }, 'form': { 'field_name': 'ncbi_taxonomy_id' }, 'multipart_form': { 'field_name': 'ncbi_taxonomy_id' }})
    

