"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from pazy import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Organism:
    UNSET='__SPEAKEASY_UNSET__'
    id: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    scientific_name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('scientific_name') }})
    phylum: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('phylum'), 'exclude': lambda f: f is None }})
    ncbi_taxonomy_id: Optional[int] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('ncbi_taxonomy_id'), 'exclude': lambda f: f is Organism.UNSET }})
    

