"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from pazy import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PatchedLiterature:
    doi: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('doi'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'doi' }, 'multipart_form': { 'field_name': 'doi' }})
    title: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('title'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'title' }, 'multipart_form': { 'field_name': 'title' }})
    authors: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('authors'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'authors' }, 'multipart_form': { 'field_name': 'authors' }})
    journal: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('journal'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'journal' }, 'multipart_form': { 'field_name': 'journal' }})
    year: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('year'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'year' }, 'multipart_form': { 'field_name': 'year' }})
    

