"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from pazy import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PatchedSubstrate:
    name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'name' }, 'multipart_form': { 'field_name': 'name' }})
    smiles: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('smiles'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'smiles' }, 'multipart_form': { 'field_name': 'smiles' }})
    inchikey: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('inchikey'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'inchikey' }, 'multipart_form': { 'field_name': 'inchikey' }})
    abbreviation: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('abbreviation'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'abbreviation' }, 'multipart_form': { 'field_name': 'abbreviation' }})
    

