"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .literature import Literature
from .organism import Organism
from .substrate import Substrate
from dataclasses_json import Undefined, dataclass_json
from pazy import utils
from typing import List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ProteinSequence:
    id: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    organisms: List[Organism] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('organisms') }})
    substrates: List[Substrate] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('substrates') }})
    literature: List[Literature] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('literature') }})
    name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name') }})
    amino_acid_sequence: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('amino_acid_sequence'), 'exclude': lambda f: f is None }})
    verified_activity: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('verified_activity'), 'exclude': lambda f: f is None }})
    

